### ISSUE TITLE
TO-DO list

### ISSUE THREAD

**Issue by LoiNguyenCS** [kelloggm/specimin#12]
This is the to-do list for Specimin:

1. Modify `UnsolvedSymbolVisitor` to create a dedicated class for the return type of each unsolved method.
2. Add Signature Checker to `UnsolvedSymbolVisitor`.
3. Add the "class-path provided" mode, where users manually provide the class-path for Specimin.
4. Add test cases for classes that has the same name as classes from `java.lang` (something like `org.foo.String`).

**Comment by LoiNguyenCS** [comment]
Professor @kelloggm, this is the to-do list for Specimin. As we discussed during our meeting, we need a to-do list to prioritize tasks. I have numbered the tasks based on the order I think we should complete them. Please let me know your opinion

**Comment by kelloggm** [comment]
@LoiNguyenCS I agree with both this list and the ordering. However, it doesn't make sense to have them in a single GitHub issue: each one is separate concern. I think you should create a new issue for each one, so that we can close the issue when it's done. Then, the issue tracker itself is the todo list.
